name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@5923a8fba3a98cf17e36583cc498d5e70a01c482 # main
        with:
          repository: openstack/ironic
          ref: d99b35dcda7df5c09621e1c1a2c4def112d1d7c6 # stable/2025.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@5923a8fba3a98cf17e36583cc498d5e70a01c482 # main
        with:
          image-name: ironic
          build-contexts: ironic=openstack/ironic
          push: ${{ github.event_name != 'pull_request' }}
